#!/bin/bash 
#SBATCH -D /global/scratch/users/peter_stokes/VariantCalling/newVC/VCF
#SBATCH -J 6_bcftoolsConcat_invariantsConcat_allChrom
#SBATCH --account=co_rosalind
#SBATCH --partition=savio2_htc
#SBATCH --qos=rosalind_htc2_normal
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=12
#SBATCH --time=72:00:00
#SBATCH --mem=128000
#SBATCH -o /global/scratch/users/peter_stokes/err_outs/6_bcftoolsConcat_invariantsConcat_allChrom.out
#SBATCH -e /global/scratch/users/peter_stokes/err_outs/6_bcftoolsConcat_invariantsConcat_allChrom.err
#SBATCH --mail-user=peter_stokes@berkeley.edu
#SBATCH --mail-type=All

module load bcftools/1.6
module load htslib/1.6

bcftools concat PS_Chapter1_Chr01_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz PS_Chapter1_Chr02_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz PS_Chapter1_Chr03_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz PS_Chapter1_Chr04_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz PS_Chapter1_Chr05_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz PS_Chapter1_Chr06_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz PS_Chapter1_Chr07_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz PS_Chapter1_Chr08_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz PS_Chapter1_Chr09_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz PS_Chapter1_Chr10_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz PS_Chapter1_Chr11_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz PS_Chapter1_Chr12_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz PS_Chapter1_Chr13_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz PS_Chapter1_Chr14_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz PS_Chapter1_Chr15_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz PS_Chapter1_Chr16_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz PS_Chapter1_Chr17_allChunks_annotated_invariantsOnly_hardFiltered.vcf.gz -Oz -o PS_Chapter1_allChrom_annotated_invariantsOnly_hardFiltered.vcf.gz

tabix -p vcf PS_Chapter1_allChrom_annotated_invariantsOnly_hardFiltered.vcf.gz