#!/bin/bash
#SBATCH -D /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome
#SBATCH -J GATK_plastome_haploCaller_05
#SBATCH --account=co_rosalind
#SBATCH --partition=savio2_htc
#SBATCH --qos=rosalind_htc2_normal
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH -o /global/scratch/users/peter_stokes/err_outs/plastome_haploCaller_05.out
#SBATCH -e /global/scratch/users/peter_stokes/err_outs/plastome_haploCaller_05.err
#SBATCH --mail-user=peter_stokes@berkeley.edu
#SBATCH --mail-type=All

module load java

/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SD1W_35.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SD1W_35.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SD1W_4.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SD1W_4.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SD1W_6.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SD1W_6.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SD2W_14.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SD2W_14.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SD2W_15.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SD2W_15.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SD2W_18.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SD2W_18.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SD2W_19.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SD2W_19.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SD2W_21.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SD2W_21.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SD2W_23.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SD2W_23.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SD2W_23R.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SD2W_23R.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SD2W_27.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SD2W_27.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SD2W_30.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SD2W_30.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SD2W_38.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SD2W_38.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SD2W_40.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SD2W_40.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SD2W_5.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SD2W_5.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SIP.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SIP.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SK1W_1.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SK1W_1.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SK1W_15.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SK1W_15.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SK1W_22.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SK1W_22.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SK1W_22R.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SK1W_22R.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SK1W_25.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SK1W_25.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SK1W_29.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SK1W_29.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SK1W_29R.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SK1W_29R.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SK1W_36.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SK1W_36.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SK1W_37.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SK1W_37.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SK1W_Q.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SK1W_Q.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Se_Purp.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Se_Purp.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Se_Strip_682a.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Se_Strip_682a.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Se_Strip_682b.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Se_Strip_682b.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Seneca.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Seneca.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Seneca_137749.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Seneca_137749.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Zuni.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Zuni.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ann01_cwIA.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ann01_cwIA.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ann04_nwAR.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ann04_nwAR.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ann05_ccNM.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ann05_ccNM.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ann06_seWY.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ann06_seWY.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ann10_ccIL.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ann10_ccIL.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ann20_seAZ.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ann20_seAZ.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ann28_swSK.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ann28_swSK.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ann29_neSD.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ann29_neSD.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ann34_cwKS.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ann34_cwKS.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ann39_ncNE.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ann39_ncNE.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ann44_ccCA.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ann44_ccCA.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/annMex_A1516.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/annMex_A1516.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/annMex_A1517.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/annMex_A1517.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/annMex_A1572.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/annMex_A1572.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/annMex_A1574.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/annMex_A1574.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/annMex_Ann261.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/annMex_Ann261.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_01_Newt_Kash_16447_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_01.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_02_Alred_32_4_98a_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_02.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_03_Putnam_32_44_257_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_03.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_04_Montgomery_4_32_34_59_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_04.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_05_Craddock_34_7_33_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_05.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_06_Green_Bluff_33_7_154_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_06.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_07_Edens_Bluff_32_3_27_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_07.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_09_a_Tularosa_4000-1-2151_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_09a.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_09_b_Tularosa_4000-1-2151_pilot_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_09b.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_10_Trinchera_Creek_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_10.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_11_a_Newt_Kash_16389_Lab_1083_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_11a.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_11_b_Newt_Kash_16389_Lab_1083_pilot_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_11b.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_11c_Newt_Kash_16389_lab_1083.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_11c.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_12_Putnum_32_44_132a_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_12.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_13_Alred_32_4_159a_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_13.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_14_Putnum_32_44_479_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_14.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_15_Agnew_Bluff_32_1_168_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_15.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_17_Newt_Kash_16447_1217_1_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_17.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_18_Newt_Kash_4000_1_10329_2_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_18.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_19_Montgomery_32_34_160_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_19.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_20_Poole_2_32_42_3_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_20.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_21_Edens_Bluff_32_3_1754b_1_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_21.g.vcf.gz --ERC GVCF
