#!/bin/bash
#SBATCH -D /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome
#SBATCH -J GATK_plastome_haploCaller_01
#SBATCH --account=co_rosalind
#SBATCH --partition=savio2_htc
#SBATCH --qos=rosalind_htc2_normal
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH -o /global/scratch/users/peter_stokes/err_outs/plastome_haploCaller_01.out
#SBATCH -e /global/scratch/users/peter_stokes/err_outs/plastome_haploCaller_01.err
#SBATCH --mail-user=peter_stokes@berkeley.edu
#SBATCH --mail-type=All

module load java

/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0810.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0810.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0820.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0820.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0830.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0830.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0835.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0835.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0849.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0849.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0854.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0854.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0867.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0867.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0874.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0874.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0880.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0880.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0882.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0882.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0898.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0898.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0908.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0908.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0918.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0918.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0927.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0927.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0931.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0931.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0946.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0946.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0956.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0956.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0957.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0957.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0959.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0959.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0962.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0962.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0963.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0963.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0964.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0964.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0972.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0972.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0975.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0975.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0978.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0978.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0981.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0981.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0985.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0985.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0986.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0986.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0992.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0992.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0996.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0996.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN0997.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN0997.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1002.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1002.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1003.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1003.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1004.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1004.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1011.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1011.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1012.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1012.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1019.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1019.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1029.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1029.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1040.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1040.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1046.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1046.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1053.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1053.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1062.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1062.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1073.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1073.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1083.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1083.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1095.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1095.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1106.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1106.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1115.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1115.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1127.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1127.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1134.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1134.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1143.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1143.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1151.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1151.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1152.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1152.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1153.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1153.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1154.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1154.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1155.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1155.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1156.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1156.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1157.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1157.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1159.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1159.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1160.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1160.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1162.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1162.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1164.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1164.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1169.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1169.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1171.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1171.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1172.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1172.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1173.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1173.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1174.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1174.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1175.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1175.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1176.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1176.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1177.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1177.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1178.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1178.g.vcf.gz --ERC GVCF
