#!/bin/bash
#SBATCH -D /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome
#SBATCH -J GATK_plastome_haploCaller_06
#SBATCH --account=co_rosalind
#SBATCH --partition=savio2_htc
#SBATCH --qos=rosalind_htc2_normal
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH -o /global/scratch/users/peter_stokes/err_outs/plastome_haploCaller_06.out
#SBATCH -e /global/scratch/users/peter_stokes/err_outs/plastome_haploCaller_06.err
#SBATCH --mail-user=peter_stokes@berkeley.edu
#SBATCH --mail-type=All

module load java

/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_22_Edens_Bluff_32_3_247a_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_22.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_23_Edens_Bluff_32_3_247b_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_23.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_25_NM_cave_4000_1_2146_Lab_3190_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_25.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_26_Alred_32_4_103b_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_26.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_27_Beaver_Pond_34_2_279_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_27.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_28_Edens_Bluff_32_3_1712_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_28.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_29_Brown_Bluff_32_10_78_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_29.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_30_Edens_Bluff_32_3_247c_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_30.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_31_Cold_Oak_Fea_54_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_31.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_32_Cloudsplitter_FS2318_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_32.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_33_Cloudsplitter_FS2280_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_33.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_35_Cloudsplitter_unk_frg_2_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_35.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_35b_Cloudsplitter_15Mf36.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_35b.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_36_Cloudsplitter_FS2316_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_36.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_36b_Cloudsplitter_FS2316.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_36b.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_36c_Cloudsplitter_FS2316.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_36c.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_36d_Cloudsplitter_FS2316.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_36d.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_37_Cloudsplitter_Level_1_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_37.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_37b_Cloudsplitter_Level_1.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_37b.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_38_Cloudsplitter_FS2353_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_38.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_38b_Cloudsplitter_FS2353.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_38b.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_39_Mammoth_Cave_B8_L_2_Str_2_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_39.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_40_Mammoth_Cave_B6_Str_2_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_40.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_41_Edens_Bluff_32_3_95a_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_41.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_42_Edens_Bluff_32_3_1701a_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_42.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_43_Edens_Bluff_32_3_1702_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_43.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_45_Edens_Bluff_32_3_1702_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_45.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_46_Edens_Bluff_32_3_1698_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_46.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_47_Edens_Bluff_32_3_1696b_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_47.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_48_Edens_Bluff_32_3_1696a_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_48.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_49_Edens_Bluff_32_3_1695_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_49.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_50_Edens_Bluff_32_3_1699a_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_50.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_51_Mammoth_Cave_B11_L_2_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_51.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_52_Cloudsplitter_FS2420_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_52.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_53_Cloudsplitter_FS1983_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_53.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_55_Cloudsplitter_Level_1_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_55.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_56_Cloudsplitter_FS2316_perianth.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_56.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_57_Cloudsplitter_Level_2_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_57.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_58_Newt_Kash_16447_1217_disk.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_58.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_59_Newt_Kash_4000_1_10329_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_59.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_60_Newt_Kash_16446_1216_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_60.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_61_a_Edens_Bluff_15478_pilot_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_61a.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_61_b_Edens_Bluff_15478_pilot_seed.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_61b.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_62_a_Salts_Cave_24135_Ky_1946_pilot_1_achene.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_62a.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_62_b_Salts_Cave_24135_Ky_1946_pilot_11_achenes.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_62b.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_63a_Bushwack_116241.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_63a.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_63b_Bushwack_116241.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_63b.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_64a_Bushwack_246194.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_64a.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_64b_Bushwack_246194.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_64b.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65a_coat_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65a_coat.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65a_endo_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65a_endo.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65b_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65b.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65c_coat_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65c_coat.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65c_endo_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65c_endo.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65d_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65d.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65e_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65e.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65f_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65f.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65g_coat_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65g_coat.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65g_endo_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65g_endo.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65h_coat_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65h_coat.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65h_endo_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65h_endo.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65i_Alred_117265_S60.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65i.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65j_coat_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65j_coat.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65j_endo_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65j_endo.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65k_coat_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65k_coat.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65k_endo_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65k_endo.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65l_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65l.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_65m_Alred_117265.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_65m.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_66a_Indian_Bluff_116506.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_66a.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/SF_79.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/SF_79.g.vcf.gz --ERC GVCF
