#!/bin/bash
#SBATCH -D /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome
#SBATCH -J GATK_plastome_haploCaller_02
#SBATCH --account=co_rosalind
#SBATCH --partition=savio2_htc
#SBATCH --qos=rosalind_htc2_normal
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH -o /global/scratch/users/peter_stokes/err_outs/plastome_haploCaller_02.out
#SBATCH -e /global/scratch/users/peter_stokes/err_outs/plastome_haploCaller_02.err
#SBATCH --mail-user=peter_stokes@berkeley.edu
#SBATCH --mail-type=All

module load java

/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1179.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1179.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1180.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1180.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1181.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1181.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1182.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1182.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1183.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1183.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1184.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1184.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1185.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1185.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1186.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1186.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1187.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1187.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1188.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1188.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1189.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1189.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1190.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1190.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1191.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1191.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1192.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1192.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1193.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1193.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1194.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1194.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1195.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1195.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1196.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1196.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1197.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1197.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1198.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1198.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1199.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1199.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1200.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1200.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1201.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1201.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1202.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1202.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1203.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1203.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1204.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1204.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1205.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1205.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1206.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1206.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1207.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1207.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1208.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1208.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1209.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1209.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1210.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1210.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1216.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1216.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1218.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1218.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1219.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1219.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1260.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1260.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1268.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1268.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1273.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1273.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1284.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1284.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1296.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1296.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1297.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1297.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1300.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1300.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1301.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1301.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1309.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1309.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1310.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1310.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1311.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1311.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1316.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1316.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1319.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1319.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1322.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1322.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1328.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1328.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1330.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1330.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1331.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1331.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1341.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1341.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1407.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1407.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1419.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1419.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1420.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1420.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1439.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1439.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ANN1501.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ANN1501.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ARG0054.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ARG0054.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ARG0169.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ARG0169.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ARG0204.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ARG0204.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Ann1238_AllReads.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Ann1238.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Anzac_Pueblo.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Anzac_Pueblo.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Ari_Broad.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Ari_Broad.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Ari_Man.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Ari_Man.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Arikara.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Arikara.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Arikara_122976.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Arikara_122976.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Arikara_126306.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Arikara_126306.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Arikara_14042_874.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Arikara_14042_874.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ED_IA1W1_6_308.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ED_IA1W1_6_308.g.vcf.gz --ERC GVCF
