#!/bin/bash
#SBATCH -D /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome
#SBATCH -J GATK_plastome_haploCaller_03
#SBATCH --account=co_rosalind
#SBATCH --partition=savio2_htc
#SBATCH --qos=rosalind_htc2_normal
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --time=24:00:00
#SBATCH -o /global/scratch/users/peter_stokes/err_outs/plastome_haploCaller_03.out
#SBATCH -e /global/scratch/users/peter_stokes/err_outs/plastome_haploCaller_03.err
#SBATCH --mail-user=peter_stokes@berkeley.edu
#SBATCH --mail-type=All

module load java

/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ED_IA2W_17.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ED_IA2W_17.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ED_KS1W9_3_342.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ED_KS1W9_3_342.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ED_KS2W24_7_43.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ED_KS2W24_7_43.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ED_MB1W16_2_283.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ED_MB1W16_2_283.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ED_MO1W30-1_114.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ED_MO1W30_1_114.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ED_ND1W27_2_288.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ED_ND1W27_2_288.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ED_SD1W11_7_237.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ED_SD1W11_7_237.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ED_SD2W30_3_360.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ED_SD2W30_3_360.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/ED_SK1W15-3_300.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/ED_SK1W15_3_300.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/HA124.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/HA124.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/HA207.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/HA207.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/HA259.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/HA259.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/HA314.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/HA314.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/HA316.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/HA316.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/HA323.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/HA323.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/HA380.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/HA380.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/HA404.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/HA404.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/HA433.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/HA433.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/HA442.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/HA442.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/HA821.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/HA821.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/HA89.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/HA89.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Havasupai.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Havasupai.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Hidatsa.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Hidatsa.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Hopi_dye_NEW.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Hopi_dye_NEW.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Hopi_mapping_NEW.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Hopi_mapping_NEW.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Hopi_real_NEW.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Hopi_real_NEW.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA1W_1.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA1W_1.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA1W_11.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA1W_11.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA1W_11R.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA1W_11R.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA1W_15.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA1W_15.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA1W_2.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA1W_2.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA1W_21.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA1W_21.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA1W_28.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA1W_28.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA1W_33.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA1W_33.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA1W_39.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA1W_39.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA1W_4.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA1W_4.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA1W_5.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA1W_5.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA2W_11.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA2W_11.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA2W_14.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA2W_14.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA2W_16.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA2W_16.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA2W_29.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA2W_29.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA2W_37.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA2W_37.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA2W_37R.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA2W_37R.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA2W_38.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA2W_38.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA2W_39.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA2W_39.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA2W_6.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA2W_6.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/IA2W_7.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/IA2W_7.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS1W_19.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS1W_19.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS1W_2.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS1W_2.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS1W_24.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS1W_24.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS1W_26.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS1W_26.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS1W_27.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS1W_27.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS1W_29.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS1W_29.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS1W_3.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS1W_3.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS1W_32.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS1W_32.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS1W_35.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS1W_35.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS1W_40.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS1W_40.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS1W_9.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS1W_9.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS2W_12.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS2W_12.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS2W_14.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS2W_14.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS2W_15.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS2W_15.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS2W_15R.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS2W_15R.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS2W_24.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS2W_24.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS2W_32.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS2W_32.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS2W_35.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS2W_35.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS2W_6.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS2W_6.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS2W_6_1R.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS2W_6_1R.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS2W_8.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS2W_8.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/KS2W_9.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/KS2W_9.g.vcf.gz --ERC GVCF
/global/home/users/peter_stokes/software/gatk-4.3.0.0/gatk --java-options "-Djava.io.tmpdir=/global/scratch/users/peter_stokes/temp_files/ -Xmx10G" HaplotypeCaller -R /global/scratch/users/peter_stokes/references/HanXRQr2.0-SUNRISE-2.1.genome.CP.fasta -I /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/bams/plastome/Laguna_Pueblo.Plastome.bam -ploidy 1 -L HanXRQCP -O /global/scratch/users/peter_stokes/Chapter1/haplotypeNetworks/gvcfs/plastome/Laguna_Pueblo.g.vcf.gz --ERC GVCF
