

setwd("/Users/peterstokes/Documents/Science/Chapter1/08_TreeMix/TreeMixOutput/Chapter1_allChrom_noRR_NF_noED_noLowCov_noInterIntraAdmix_noBadMexCult_wMexWild_wCAAZ_D4_Bi_plinked_G2_M5_LD_Pruned_TreeMixInput_SampleSizeCorrection_noNoss") # of course this needs to be adjusted
setwd("/Users/peterstokes/Documents/Science/Chapter1/08_TreeMix/TreeMixOutput/Chapter1_allChrom_noRR_NF_noED_noLowCov_noInterIntraAdmix_noBadMexCult_wMexWild_wCAAZ_D4_Bi_plinked_G2_M5_LD_Pruned_TreeMixInput_SampleSizeCorrection_k500") # of course this needs to be adjusted
setwd("/Users/peterstokes/Documents/Science/Chapter1/08_TreeMix/TreeMixOutput/TreeMix_test") # of course this needs to be adjusted

#PS_Chapter1_biallelic_allChrom_allSamples_plinked_mac_1_LD0_1_Pruned_TreeMixPrepReady_reducedPopAssignments.1

library(RColorBrewer)
library(R.utils)
source("/Users/peterstokes/Documents/Science/Chapter1/08_TreeMix/scripts/plotting_funcs.R") # here you need to add the path

prefix="Chapter1_allChrom_noRR_NF_noED_noLowCov_noInterIntraAdmix_noBadMexCult_wMexWild_D4_Bi_plinked_G2_M5_LD_Pruned_TreeMixInput_SampleSizeCorrection_m0_iter_1"
plot_tree(prefix)

prefix="Chapter1_allChrom_noRR_NF_noED_noLowCov_noInterIntraAdmix_noBadMexCult_wMexWild_wCAAZ_D4_Bi_plinked_G2_M5_LD_Pruned_TreeMixInput_SampleSizeCorrection_m1_noNoss_iter_1"
plot_tree(prefix)

prefix="Chapter1_allChrom_noRR_NF_noED_noLowCov_noInterIntraAdmix_noBadMexCult_wMexWild_wCAAZ_D4_Bi_plinked_G2_M5_LD_Pruned_TreeMixInput_SampleSizeCorrection_m0_noNoss_iter_3"
plot_tree(prefix)

prefix="Chapter1_allChrom_noRR_NF_noED_noLowCov_noInterIntraAdmix_noBadMexCult_wMexWild_wCAAZ_D4_Bi_plinked_G2_M5_LD_Pruned_TreeMixInput_SampleSizeCorrection_m0_noNoss_iter_4"
plot_tree(prefix)

prefix="Chapter1_allChrom_noRR_NF_noED_noLowCov_noInterIntraAdmix_noBadMexCult_wMexWild_wCAAZ_D4_Bi_plinked_G2_M5_LD_Pruned_TreeMixInput_SampleSizeCorrection_m0_noNoss_iter_5"
plot_tree(prefix)

prefix="Chapter1_allChrom_noRR_NF_noED_noLowCov_noInterIntraAdmix_noBadMexCult_wMexWild_wCAAZ_D4_Bi_plinked_G2_M5_LD_Pruned_TreeMixInput_SampleSizeCorrection_m0_noNoss_iter_6"
plot_tree(prefix)

prefix="Chapter1_allChrom_noRR_NF_noED_noLowCov_noInterIntraAdmix_noBadMexCult_wMexWild_wCAAZ_D4_Bi_plinked_G2_M5_LD_Pruned_TreeMixInput_SampleSizeCorrection_m0_noNoss_iter_7"
plot_tree(prefix)

prefix="Chapter1_allChrom_noRR_NF_noED_noLowCov_noInterIntraAdmix_noBadMexCult_wMexWild_wCAAZ_D4_Bi_plinked_G2_M5_LD_Pruned_TreeMixInput_SampleSizeCorrection_m0_noNoss_iter_8"
plot_tree(prefix)

prefix="Chapter1_allChrom_noRR_NF_noED_noLowCov_noInterIntraAdmix_noBadMexCult_wMexWild_wCAAZ_D4_Bi_plinked_G2_M5_LD_Pruned_TreeMixInput_SampleSizeCorrection_m0_noNoss_iter_9"
plot_tree(prefix)

prefix="Chapter1_allChrom_noRR_NF_noED_noLowCov_noInterIntraAdmix_noBadMexCult_wMexWild_wCAAZ_D4_Bi_plinked_G2_M5_LD_Pruned_TreeMixInput_SampleSizeCorrection_m0_noNoss_iter_10"
plot_tree(prefix)
